### ISSUE TITLE
OOF

### ISSUE THREAD

**Issue by MancaZerovnikMekuc** [giaylenia/OCTA_segm_study#1]
I am writing regarding your comment about OOF function requirement. Is it available somewhere or can you provide your implementation?
I am writing about `oofseg ` function which you use. 

Best regards and thank you for your work.

**Comment by giaylenia** [comment]
Hi, thank you for you comment. 
I am using the code kindly shared by  Ang Li, author of the paper https://www.osapublishing.org/boe/abstract.cfm?uri=boe-8-12-5604. Since it is not my code, I can’t share it, however you can email the author. 
Let me know then if you have any trouble in  running my code or setting the parameters. 

Best wishes
